// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3IwphtUVIjMSsMsy2PnYEzuLmMebObYc',
    appId: '1:538875524233:web:edea80ce8717d507778258',
    messagingSenderId: '538875524233',
    projectId: 'ravanellifinaldatabase',
    authDomain: 'ravanellifinaldatabase.firebaseapp.com',
    storageBucket: 'ravanellifinaldatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QL1t8qZZSICg7xKO_naNu6XI86n4Esc',
    appId: '1:538875524233:android:68c77dce4f3f5e2f778258',
    messagingSenderId: '538875524233',
    projectId: 'ravanellifinaldatabase',
    storageBucket: 'ravanellifinaldatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QlR8ZJ55lgqCapJHsFYIykQCVpBXUr4',
    appId: '1:538875524233:ios:d4a9b43fe39386d0778258',
    messagingSenderId: '538875524233',
    projectId: 'ravanellifinaldatabase',
    storageBucket: 'ravanellifinaldatabase.appspot.com',
    iosClientId: '538875524233-89bifritic8jvevm5enurtst6kju4739.apps.googleusercontent.com',
    iosBundleId: 'com.example.ravanelliProjetoFinalWebdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QlR8ZJ55lgqCapJHsFYIykQCVpBXUr4',
    appId: '1:538875524233:ios:d4a9b43fe39386d0778258',
    messagingSenderId: '538875524233',
    projectId: 'ravanellifinaldatabase',
    storageBucket: 'ravanellifinaldatabase.appspot.com',
    iosClientId: '538875524233-89bifritic8jvevm5enurtst6kju4739.apps.googleusercontent.com',
    iosBundleId: 'com.example.ravanelliProjetoFinalWebdev',
  );
}
